<?xml version="1.0" encoding="utf-8"?><Database Name="QLPK" Class="QLPKDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-K10406A5\SQLEXPRESS;Initial Catalog=QLPK;User ID=sa" SettingsObjectName="BLL_DAL.Properties.Settings" SettingsPropertyName="QLPKConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BENH_NHAN" Member="BENH_NHANs">
    <Type Name="BENH_NHAN">
      <Column Name="BN_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BN_TEN" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BN_NGAYSINH" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="BN_SDT" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="BN_GIOITINH" Type="System.String" DbType="NVarChar(3) NOT NULL" CanBeNull="false" />
      <Column Name="BN_DIACHI" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="BENH_NHAN_DON_THUOC_DICHVU" Member="DON_THUOC_DICHVUs" ThisKey="BN_ID" OtherKey="BN_ID" Type="DON_THUOC_DICHVU" />
    </Type>
  </Table>
  <Table Name="dbo.THUOC" Member="THUOCs">
    <Type Name="THUOC">
      <Column Name="THUOC_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="THUOC_TENTHUOC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DANHMUC_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="THUOC_DVT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="THUOC_SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="THUOC_DONGIA" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="THUOC_HANSUDUNG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="THUOC_NHACUNGCAP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="THUOC_NGAYNHAP" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="THUOC_CHIDINH" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="THUOC_CHI_TIET_DON_THUOC" Member="CHI_TIET_DON_THUOCs" ThisKey="THUOC_ID" OtherKey="THUOC_ID" Type="CHI_TIET_DON_THUOC" />
      <Association Name="DANHMUC_THUOC_THUOC" Member="DANHMUC_THUOC" ThisKey="DANHMUC_ID" OtherKey="DANHMUC_ID" Type="DANHMUC_THUOC" IsForeignKey="true" />
      <Association Name="NHA_CUNG_CAP_THUOC" Member="NHA_CUNG_CAP" ThisKey="THUOC_NHACUNGCAP" OtherKey="NCC_ID" Type="NHA_CUNG_CAP" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHI_TIET_DICH_VU" Member="CHI_TIET_DICH_VUs">
    <Type Name="CHI_TIET_DICH_VU">
      <Column Name="CHITIET_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DONDV_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DICHVU_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DICH_VU_CHI_TIET_DICH_VU" Member="DICH_VU" ThisKey="DONDV_ID" OtherKey="DICHVU_ID" Type="DICH_VU" IsForeignKey="true" />
      <Association Name="DON_THUOC_DICHVU_CHI_TIET_DICH_VU" Member="DON_THUOC_DICHVU" ThisKey="DONDV_ID" OtherKey="DONTHUOC_ID" Type="DON_THUOC_DICHVU" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHI_TIET_DON_THUOC" Member="CHI_TIET_DON_THUOCs">
    <Type Name="CHI_TIET_DON_THUOC">
      <Column Name="CHITIET_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DONTHUOC_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="THUOC_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="THUOC_CHI_TIET_DON_THUOC" Member="THUOC" ThisKey="THUOC_ID" OtherKey="THUOC_ID" Type="THUOC" IsForeignKey="true" />
      <Association Name="DON_THUOC_DICHVU_CHI_TIET_DON_THUOC" Member="DON_THUOC_DICHVU" ThisKey="DONTHUOC_ID" OtherKey="DONTHUOC_ID" Type="DON_THUOC_DICHVU" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DANHMUC_THUOC" Member="DANHMUC_THUOCs">
    <Type Name="DANHMUC_THUOC">
      <Column Name="DANHMUC_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DANHMUC_TEN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DANHMUC_MOTA" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="DANHMUC_THUOC_THUOC" Member="THUOCs" ThisKey="DANHMUC_ID" OtherKey="DANHMUC_ID" Type="THUOC" />
    </Type>
  </Table>
  <Table Name="dbo.DICH_VU" Member="DICH_VUs">
    <Type Name="DICH_VU">
      <Column Name="DICHVU_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DICHVU_TEN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DICHVU_DONGIA" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="DICH_VU_CHI_TIET_DICH_VU" Member="CHI_TIET_DICH_VUs" ThisKey="DICHVU_ID" OtherKey="DONDV_ID" Type="CHI_TIET_DICH_VU" />
    </Type>
  </Table>
  <Table Name="dbo.DM_MANHINH" Member="DM_MANHINHs">
    <Type Name="DM_MANHINH">
      <Column Name="MAMANHINH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENMANHINH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="DM_MANHINH_QL_PHANQUYEN" Member="QL_PHANQUYENs" ThisKey="MAMANHINH" OtherKey="MAMANHINH" Type="QL_PHANQUYEN" />
    </Type>
  </Table>
  <Table Name="dbo.DON_THUOC_DICHVU" Member="DON_THUOC_DICHVUs">
    <Type Name="DON_THUOC_DICHVU">
      <Column Name="DONTHUOC_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NGAYLAP" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NV_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BN_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PK_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TONGTIEN" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Association Name="DON_THUOC_DICHVU_CHI_TIET_DICH_VU" Member="CHI_TIET_DICH_VUs" ThisKey="DONTHUOC_ID" OtherKey="DONDV_ID" Type="CHI_TIET_DICH_VU" />
      <Association Name="DON_THUOC_DICHVU_CHI_TIET_DON_THUOC" Member="CHI_TIET_DON_THUOCs" ThisKey="DONTHUOC_ID" OtherKey="DONTHUOC_ID" Type="CHI_TIET_DON_THUOC" />
      <Association Name="BENH_NHAN_DON_THUOC_DICHVU" Member="BENH_NHAN" ThisKey="BN_ID" OtherKey="BN_ID" Type="BENH_NHAN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LICH_LAM_VIEC" Member="LICH_LAM_VIECs">
    <Type Name="LICH_LAM_VIEC">
      <Column Name="LICHLAMVIEC_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NV_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PK_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGAYLAMVIEC" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="NHAN_VIEN_LICH_LAM_VIEC" Member="NHAN_VIEN" ThisKey="NV_ID" OtherKey="NV_ID" Type="NHAN_VIEN" IsForeignKey="true" />
      <Association Name="PHONG_KHAM_LICH_LAM_VIEC" Member="PHONG_KHAM" ThisKey="PK_ID" OtherKey="PHONGKHAM_ID" Type="PHONG_KHAM" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NHA_CUNG_CAP" Member="NHA_CUNG_CAPs">
    <Type Name="NHA_CUNG_CAP">
      <Column Name="NCC_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NCC_TEN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NCC_DIACHI" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NCC_SDT" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="NHA_CUNG_CAP_THUOC" Member="THUOCs" ThisKey="NCC_ID" OtherKey="THUOC_NHACUNGCAP" Type="THUOC" />
      <Association Name="NHA_CUNG_CAP_THIET_BI" Member="THIET_BIs" ThisKey="NCC_ID" OtherKey="NCC_ID" Type="THIET_BI" />
    </Type>
  </Table>
  <Table Name="dbo.NHAN_VIEN" Member="NHAN_VIENs">
    <Type Name="NHAN_VIEN">
      <Column Name="NV_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NV_TEN" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NV_NGAYSINH" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="NV_EMAIL" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NV_GIOITINH" Type="System.String" DbType="NVarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="NV_SDT" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="NV_ANH" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NV_BANGCAP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NV_CHUCVU" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NV_CHUYENMON" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="NHAN_VIEN_LICH_LAM_VIEC" Member="LICH_LAM_VIECs" ThisKey="NV_ID" OtherKey="NV_ID" Type="LICH_LAM_VIEC" />
    </Type>
  </Table>
  <Table Name="dbo.PHONG_KHAM" Member="PHONG_KHAMs">
    <Type Name="PHONG_KHAM">
      <Column Name="PHONGKHAM_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PHONGKHAM_CHUYENKHOA" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HOATDONG" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SOLUONGBENHNHAN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="PHONG_KHAM_LICH_LAM_VIEC" Member="LICH_LAM_VIECs" ThisKey="PHONGKHAM_ID" OtherKey="PK_ID" Type="LICH_LAM_VIEC" />
    </Type>
  </Table>
  <Table Name="dbo.QL_NGUOIDUNG" Member="QL_NGUOIDUNGs">
    <Type Name="QL_NGUOIDUNG">
      <Column Name="TENDANGNHAP" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MATKHAU" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="HOATDONG" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NV_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="QL_NGUOIDUNG_QL_NGUOIDUNGNHOMNGUOIDUNG" Member="QL_NGUOIDUNGNHOMNGUOIDUNGs" ThisKey="TENDANGNHAP" OtherKey="TENDANGNHAP" Type="QL_NGUOIDUNGNHOMNGUOIDUNG" />
    </Type>
  </Table>
  <Table Name="dbo.QL_NGUOIDUNGNHOMNGUOIDUNG" Member="QL_NGUOIDUNGNHOMNGUOIDUNGs">
    <Type Name="QL_NGUOIDUNGNHOMNGUOIDUNG">
      <Column Name="TENDANGNHAP" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MANHOMNGUOIDUNG" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="QL_NGUOIDUNG_QL_NGUOIDUNGNHOMNGUOIDUNG" Member="QL_NGUOIDUNG" ThisKey="TENDANGNHAP" OtherKey="TENDANGNHAP" Type="QL_NGUOIDUNG" IsForeignKey="true" />
      <Association Name="QL_NHOMNGUOIDUNG_QL_NGUOIDUNGNHOMNGUOIDUNG" Member="QL_NHOMNGUOIDUNG" ThisKey="MANHOMNGUOIDUNG" OtherKey="MANHOM" Type="QL_NHOMNGUOIDUNG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QL_NHOMNGUOIDUNG" Member="QL_NHOMNGUOIDUNGs">
    <Type Name="QL_NHOMNGUOIDUNG">
      <Column Name="MANHOM" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENNHOM" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="QL_NHOMNGUOIDUNG_QL_NGUOIDUNGNHOMNGUOIDUNG" Member="QL_NGUOIDUNGNHOMNGUOIDUNGs" ThisKey="MANHOM" OtherKey="MANHOMNGUOIDUNG" Type="QL_NGUOIDUNGNHOMNGUOIDUNG" />
      <Association Name="QL_NHOMNGUOIDUNG_QL_PHANQUYEN" Member="QL_PHANQUYENs" ThisKey="MANHOM" OtherKey="MANHOMNGUOIDUNG" Type="QL_PHANQUYEN" />
    </Type>
  </Table>
  <Table Name="dbo.QL_PHANQUYEN" Member="QL_PHANQUYENs">
    <Type Name="QL_PHANQUYEN">
      <Column Name="MANHOMNGUOIDUNG" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAMANHINH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="COQUYEN" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="DM_MANHINH_QL_PHANQUYEN" Member="DM_MANHINH" ThisKey="MAMANHINH" OtherKey="MAMANHINH" Type="DM_MANHINH" IsForeignKey="true" />
      <Association Name="QL_NHOMNGUOIDUNG_QL_PHANQUYEN" Member="QL_NHOMNGUOIDUNG" ThisKey="MANHOMNGUOIDUNG" OtherKey="MANHOM" Type="QL_NHOMNGUOIDUNG" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.THIET_BI" Member="THIET_BIs">
    <Type Name="THIET_BI">
      <Column Name="THIETBI_ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="THIETBI_TEN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="THIETBI_DVT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NCC_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PK_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="THIETBI_SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="THIETBI_DONGIA" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="THIETBI_XUATXU" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="NHA_CUNG_CAP_THIET_BI" Member="NHA_CUNG_CAP" ThisKey="NCC_ID" OtherKey="NCC_ID" Type="NHA_CUNG_CAP" IsForeignKey="true" />
    </Type>
  </Table>
</Database>